[project]
name = "temporal"
authors = [
    { name = "Datahenge LLC", email = "brian@datahenge.com"},
]
description = "Time after Time"
dynamic = [ "version" ]
readme = "README.md"
requires-python = ">=3.10,<3.13"

dependencies = [
    "frappe >= 15,<16",
    "pytz-deprecation-shim",
    "temporal-lib == 0.0.9",
]

[tool.setuptools.dynamic]
version = {attr = "temporal.__version__"}

